const words = [
    { en: "Piece of cake", ja: "朝飯前、とても簡単" },
    { en: "Break a leg", ja: "幸運を祈る（主にパフォーマンス前）" },
    { en: "Hit the books", ja: "猛勉強する" },
    { en: "Call it a day", ja: "今日の仕事を切り上げる" },
    { en: "Under the weather", ja: "具合が悪い" },
    { en: "Spill the beans", ja: "秘密を漏らす" },
    { en: "Bite the bullet", ja: "嫌なことを我慢してやる" },
    { en: "The best of both worlds", ja: "いいとこ取り" },
    { en: "Cost an arm and a leg", ja: "非常に高価である" },
    { en: "Let the cat out of the bag", ja: "うっかり秘密を漏らす" },
    { en: "Feeling blue", ja: "落ち込んでいる" },
    { en: "See eye to eye", ja: "意見が一致する" },
    { en: "Once in a blue moon", ja: "ごく稀に" },
    { en: "When pigs fly", ja: "あり得ないこと" },
    { en: "To cut a long story short", ja: "手短に言うと" },
    { en: "Miss the boat", ja: "好機を逃す" },
    { en: "Beat around the bush", ja: "遠回しに言う" },
    { en: "A blessing in disguise", ja: "不幸に見えて実は幸運なこと" },
    { en: "No pain, no gain", ja: "苦労なくして得られるものはない" },
    { en: "Pull someone's leg", ja: "からかう" },
    { en: "Wrap your head around something", ja: "理解する" },
    { en: "Get out of hand", ja: "収拾がつかなくなる" },
    { en: "Hang in there", ja: "諦めずに頑張る" },
    { en: "So far so good", ja: "今のところ順調" },
    { en: "Get your act together", ja: "しっかりする、行動を改める" },
    { en: "It's not rocket science", ja: "そんなに難しくない" },
    { en: "Make a long story short", ja: "手短に話す" },
    { en: "Time flies", ja: "時間が経つのは早い" },
    { en: "Your guess is as good as mine", ja: "私にもさっぱりわからない" },
    { en: "A dime a dozen", ja: "ありふれたもの" },
    { en: "Better late than never", ja: "遅れてもやらないよりマシ" },
    { en: "Break the ice", ja: "緊張をほぐす、場を和ませる" },
    { en: "Easy does it", ja: "慎重にやる、落ち着いて" },
    { en: "Get something off your chest", ja: "胸のつかえを下ろす、打ち明ける" },
    { en: "Go back to the drawing board", ja: "最初からやり直す" },
    { en: "Hit the sack", ja: "寝る" },
    { en: "It takes two to tango", ja: "どっちもどっち、責任は双方にある" },
    { en: "Jump on the bandwagon", ja: "時流に乗る、多勢に加勢する" },
    { en: "Leave no stone unturned", ja: "あらゆる手を尽くす" },
    { en: "Let sleeping dogs lie", ja: "波風を立てない" },
    { en: "On the ball", ja: "機敏で、状況をよく把握して" },
    { en: "Pull yourself together", ja: "落ち着く、気を取り直す" },
    { en: "Speak of the devil", ja: "噂をすれば影" },
    { en: "That's the last straw", ja: "仏の顔も三度まで（我慢の限界）" },
    { en: "The elephant in the room", ja: "見て見ぬふりをされている大きな問題" },
    { en: "Throw in the towel", ja: "降参する、諦める" },
    { en: "Through thick and thin", ja: "良い時も悪い時も" },
    { en: "Time is money", ja: "時は金なり" },
    { en: "To make matters worse", ja: "さらに悪いことに" },
    { en: "Under the table", ja: "内密に、不正に" },
    { en: "Up in the air", ja: "未定である" },
    { en: "We'll cross that bridge when we come to it", ja: "その時になったら考えよう" },
    { en: "You can say that again", ja: "全くその通りだ" },
    { en: "Actions speak louder than words", ja: "行動は言葉よりも雄弁である" },
    { en: "Add insult to injury", ja: "泣きっ面に蜂" },
    { en: "Barking up the wrong tree", ja: "見当違いをしている" },
    { en: "Bite off more than you can chew", ja: "手に余ることをしようとする" },
    { en: "Burn the midnight oil", ja: "夜遅くまで働く・勉強する" },
    { en: "By the skin of your teeth", ja: "間一髪で" },
    { en: "Caught between a rock and a hard place", ja: "板挟みになって" },
    { en: "Costs an arm and a leg", ja: "非常に高い" },
    { en: "Cut corners", ja: "手抜きをする、節約する" },
    { en: "Devil's advocate", ja: "あえて反論する人" },
    { en: "Don't count your chickens before they hatch", ja: "捕らぬ狸の皮算用" },
    { en: "Don't give up the day job", ja: "（下手だから）本業を辞めない方がいいよ" },
    { en: "Don't put all your eggs in one basket", ja: "危険を分散せよ" },
    { en: "Drastic times call for drastic measures", ja: "非常時には非常手段が必要だ" },
    { en: "Every cloud has a silver lining", ja: "どんな悪いことにも良い側面がある" },
    { en: "Far cry from", ja: "～とは大違いである" },
    { en: "Give someone the benefit of the doubt", ja: "（証拠がないので）人を信じる" },
    { en: "Hear it on the grapevine", ja: "噂で聞く" },
    { en: "Hit the nail on the head", ja: "図星を指す、的を射る" },
    { en: "In the heat of the moment", ja: "興奮して、かっとなって" },
    { en: "It takes one to know one", ja: "お互い様だ" },
    { en: "Keep something at bay", ja: "～を寄せ付けない" },
    { en: "Kill two birds with one stone", ja: "一石二鳥" },
    { en: "Let off steam", ja: "ストレスを発散する" },
    { en: "Look before you leap", ja: "転ばぬ先の杖" },
    { en: "Make ends meet", ja: "やりくりする、収支を合わせる" },
    { en: "Method to my madness", ja: "変に見えても考えがある" },
    { en: "Not a spark of decency", ja: "良心のかけらもない" },
    { en: "Off the hook", ja: "責任を逃れて、苦境を脱して" },
    { en: "Off the record", ja: "非公式に、オフレコで" },
    { en: "Once bitten, twice shy", ja: "あつものに懲りてなますを吹く" },
    { en: "Out of the blue", ja: "突然に" },
    { en: "Picture paints a thousand words", ja: "百聞は一見に如かず" },
    { en: "Put wool over other people's eyes", ja: "人を騙す" },
    { en: "Rain on someone's parade", ja: "人の楽しみを台無しにする" },
    { en: "Skeletons in the closet", ja: "隠しておきたい秘密" },
    { en: "Steal someone's thunder", ja: "人のお株を奪う" },
    { en: "Take with a grain of salt", ja: "話半分に聞く" },
    { en: "Taste of your own medicine", ja: "しっぺ返し" },
    { en: "The ball is in your court", ja: "次はあなたの番だ" },
    { en: "The whole nine yards", ja: "何もかも、すべて" },
    { en: "Throw caution to the wind", ja: "思い切ってやる" },
    { en: "Variety is the spice of life", ja: "変化は人生のスパイス" },
    { en: "Wear your heart on your sleeve", ja: "感情を露わにする" },
    { en: "You can't judge a book by its cover", ja: "人は見かけによらぬもの" },
    { en: "Zero tolerance", ja: "断固として許さないこと" },
    { en: "A hot potato", ja: "厄介な問題" },
    { en: "Against the clock", ja: "時間を争って" },
    { en: "At the drop of a hat", ja: "即座に" },
    { en: "Back to square one", ja: "振り出しに戻る" }
];
