const words = {
    beginner: [
        { en: "What's up?", ja: "調子はどう？" },
        { en: "No worries", ja: "心配ないよ、どういたしまして" },
        { en: "My bad", ja: "ごめん、私のミスだ" },
        { en: "Hang out", ja: "遊ぶ、時間を過ごす" },
        { en: "Chill out", ja: "落ち着く、リラックスする" },
        { en: "Gotcha", ja: "わかった" },
        { en: "Same here", ja: "私も同じ" },
        { en: "No way!", ja: "まさか！信じられない！" },
        { en: "You bet", ja: "もちろん、どういたしまして" },
        { en: "I'm down", ja: "いいよ、賛成" },
        { en: "Count me in", ja: "仲間に入れて、参加するよ" },
        { en: "It's up to you", ja: "君次第だ" },
        { en: "Take it easy", ja: "気楽にいこう、じゃあね" },
        { en: "Long time no see", ja: "久しぶり" },
        { en: "How come?", ja: "どうして？" },
        { en: "Fingers crossed", ja: "幸運を祈る" },
        { en: "Good for you", ja: "よかったね" },
        { en: "I guess so", ja: "そうだと思う" },
        { en: "No clue", ja: "手がかりがない、全然わからない" },
        { en: "Sort of", ja: "まあね、ある程度は" },
        { en: "Kind of", ja: "まあね、ちょっとね" },
        { en: "Keep in touch", ja: "連絡を取り合おう" },
        { en: "Have a good one", ja: "よい一日を" },
        { en: "Sounds good", ja: "いいね" },
        { en: "Never mind", ja: "気にしないで、なんでもない" },
        { en: "Go ahead", ja: "どうぞ" },
        { en: "After you", ja: "お先にどうぞ" },
        { en: "Look out!", ja: "危ない！" },
        { en: "Watch out!", ja: "気をつけて！" },
        { en: "Hurry up", ja: "急いで" },
        { en: "Calm down", ja: "落ち着いて" },
        { en: "Hang on", ja: "ちょっと待って" },
        { en: "Hold on", ja: "待って" },
        { en: "Check it out", ja: "見てみて" },
        { en: "Figure out", ja: "解決する、理解する" },
        { en: "Find out", ja: "見つける、知る" },
        { en: "Point out", ja: "指摘する" },
        { en: "Run out of", ja: "～を使い果たす" },
        { en: "Give up", ja: "諦める" },
        { en: "Give in", ja: "降参する、屈する" },
        { en: "Show up", ja: "現れる" },
        { en: "Turn up", ja: "現れる、（音量を）上げる" },
        { en: "Turn down", ja: "断る、（音量を）下げる" },
        { en: "Look for", ja: "探す" },
        { en: "Look after", ja: "世話をする" },
        { en: "Look forward to", ja: "楽しみにする" },
        { en: "Get along with", ja: "仲良くやる" },
        { en: "Catch up", ja: "追いつく、近況を話し合う" },
        { en: "Keep up", ja: "ついていく、続ける" },
        { en: "Make up", ja: "仲直りする、でっち上げる" },
        { en: "Break up", ja: "別れる" },
        { en: "Call off", ja: "中止する" },
        { en: "Carry on", ja: "続ける" },
        { en: "Put off", ja: "延期する" },
        { en: "Pick up", ja: "拾う、迎えに行く" },
        { en: "Drop off", ja: "降ろす、置いていく" },
        { en: "Show off", ja: "見せびらかす" },
        { en: "Pay back", ja: "返済する、仕返しする" },
        { en: "Run into", ja: "偶然出会う" },
        { en: "Come across", ja: "偶然見つける" },
        { en: "Get over", ja: "乗り越える、回復する" },
        { en: "Get used to", ja: "慣れる" },
        { en: "Look into", ja: "調査する" },
        { en: "Work out", ja: "運動する、解決する" },
        { en: "Pass out", ja: "気絶する" },
        { en: "Black out", ja: "意識を失う" },
        { en: "Freak out", ja: "パニックになる" },
        { en: "Piss off", ja: "怒らせる" },
        { en: "Screw up", ja: "失敗する（スラング）" },
        { en: "Mess up", ja: "台無しにする" },
        { en: "Rip off", ja: "ぼったくり" },
        { en: "Hang up", ja: "電話を切る" },
        { en: "Hold your horses", ja: "落ち着いて、焦るな" },
        { en: "Just kidding", ja: "冗談だよ" },
        { en: "No offense", ja: "悪気はないよ" },
        { en: "None of your business", ja: "大きなお世話だ" },
        { en: "Mind your own business", ja: "自分のことを気にしろ（干渉するな）" },
        { en: "So what?", ja: "だから何？" },
        { en: "Who cares?", ja: "知ったことか" },
        { en: "Why not?", ja: "もちろん、いいじゃないか" },
        { en: "Beats me", ja: "わからない" },
        { en: "Get real", ja: "現実を見ろ" },
        { en: "Get a life", ja: "もっとマシな生活をしろ（干渉するな）" },
        { en: "Way to go", ja: "よくやった" },
        { en: "Good job", ja: "よくやった" },
        { en: "Keep it up", ja: "その調子で" },
        { en: "Take your time", ja: "ゆっくりでいいよ" },
        { en: "Make yourself at home", ja: "くつろいでね" },
        { en: "Help yourself", ja: "自由に取って食べてね" },
        { en: "Let me see", ja: "えーっと（考え中）" },
        { en: "I'm broke", ja: "金欠だ" },
        { en: "I'm starving", ja: "腹ペコだ" },
        { en: "I'm stuffed", ja: "お腹いっぱいだ" },
        { en: "I'm exhausted", ja: "ヘトヘトだ" },
        { en: "Sleep on it", ja: "一晩考える" },
        { en: "Play it cool", ja: "冷静を装う" },
        { en: "Don't mention it", ja: "どういたしまして" },
        { en: "It's on me", ja: "私が奢るよ" }
    ],
    intermediate: [
        { en: "Piece of cake", ja: "朝飯前、とても簡単" },
        { en: "Break a leg", ja: "幸運を祈る（主にパフォーマンス前）" },
        { en: "Hit the books", ja: "猛勉強する" },
        { en: "Call it a day", ja: "今日の仕事を切り上げる" },
        { en: "Under the weather", ja: "具合が悪い" },
        { en: "Spill the beans", ja: "秘密を漏らす" },
        { en: "Bite the bullet", ja: "嫌なことを我慢してやる" },
        { en: "The best of both worlds", ja: "いいとこ取り" },
        { en: "Cost an arm and a leg", ja: "非常に高価である" },
        { en: "Let the cat out of the bag", ja: "うっかり秘密を漏らす" },
        { en: "Feeling blue", ja: "落ち込んでいる" },
        { en: "See eye to eye", ja: "意見が一致する" },
        { en: "Once in a blue moon", ja: "ごく稀に" },
        { en: "When pigs fly", ja: "あり得ないこと" },
        { en: "To cut a long story short", ja: "手短に言うと" },
        { en: "Miss the boat", ja: "好機を逃す" },
        { en: "Beat around the bush", ja: "遠回しに言う" },
        { en: "A blessing in disguise", ja: "不幸に見えて実は幸運なこと" },
        { en: "No pain, no gain", ja: "苦労なくして得られるものはない" },
        { en: "Pull someone's leg", ja: "からかう" },
        { en: "Wrap your head around something", ja: "理解する" },
        { en: "Get out of hand", ja: "収拾がつかなくなる" },
        { en: "Hang in there", ja: "諦めずに頑張る" },
        { en: "So far so good", ja: "今のところ順調" },
        { en: "Get your act together", ja: "しっかりする、行動を改める" },
        { en: "It's not rocket science", ja: "そんなに難しくない" },
        { en: "Make a long story short", ja: "手短に話す" },
        { en: "Time flies", ja: "時間が経つのは早い" },
        { en: "Your guess is as good as mine", ja: "私にもさっぱりわからない" },
        { en: "A dime a dozen", ja: "ありふれたもの" },
        { en: "Better late than never", ja: "遅れてもやらないよりマシ" },
        { en: "Break the ice", ja: "緊張をほぐす、場を和ませる" },
        { en: "Easy does it", ja: "慎重にやる、落ち着いて" },
        { en: "Get something off your chest", ja: "胸のつかえを下ろす、打ち明ける" },
        { en: "Go back to the drawing board", ja: "最初からやり直す" },
        { en: "Hit the sack", ja: "寝る" },
        { en: "It takes two to tango", ja: "どっちもどっち、責任は双方にある" },
        { en: "Jump on the bandwagon", ja: "時流に乗る、多勢に加勢する" },
        { en: "Leave no stone unturned", ja: "あらゆる手を尽くす" },
        { en: "Let sleeping dogs lie", ja: "波風を立てない" },
        { en: "On the ball", ja: "機敏で、状況をよく把握して" },
        { en: "Pull yourself together", ja: "落ち着く、気を取り直す" },
        { en: "Speak of the devil", ja: "噂をすれば影" },
        { en: "That's the last straw", ja: "仏の顔も三度まで（我慢の限界）" },
        { en: "The elephant in the room", ja: "見て見ぬふりをされている大きな問題" },
        { en: "Throw in the towel", ja: "降参する、諦める" },
        { en: "Through thick and thin", ja: "良い時も悪い時も" },
        { en: "Time is money", ja: "時は金なり" },
        { en: "To make matters worse", ja: "さらに悪いことに" },
        { en: "Under the table", ja: "内密に、不正に" },
        { en: "Up in the air", ja: "未定である" },
        { en: "We'll cross that bridge when we come to it", ja: "その時になったら考えよう" },
        { en: "You can say that again", ja: "全くその通りだ" },
        { en: "Actions speak louder than words", ja: "行動は言葉よりも雄弁である" },
        { en: "Add insult to injury", ja: "泣きっ面に蜂" },
        { en: "Barking up the wrong tree", ja: "見当違いをしている" },
        { en: "Bite off more than you can chew", ja: "手に余ることをしようとする" },
        { en: "Burn the midnight oil", ja: "夜遅くまで働く・勉強する" },
        { en: "By the skin of your teeth", ja: "間一髪で" },
        { en: "Caught between a rock and a hard place", ja: "板挟みになって" },
        { en: "Costs an arm and a leg", ja: "非常に高い" },
        { en: "Cut corners", ja: "手抜きをする、節約する" },
        { en: "Devil's advocate", ja: "あえて反論する人" },
        { en: "Don't count your chickens before they hatch", ja: "捕らぬ狸の皮算用" },
        { en: "Don't give up the day job", ja: "（下手だから）本業を辞めない方がいいよ" },
        { en: "Don't put all your eggs in one basket", ja: "危険を分散せよ" },
        { en: "Drastic times call for drastic measures", ja: "非常時には非常手段が必要だ" },
        { en: "Every cloud has a silver lining", ja: "どんな悪いことにも良い側面がある" },
        { en: "Far cry from", ja: "～とは大違いである" },
        { en: "Give someone the benefit of the doubt", ja: "（証拠がないので）人を信じる" },
        { en: "Hear it on the grapevine", ja: "噂で聞く" },
        { en: "Hit the nail on the head", ja: "図星を指す、的を射る" },
        { en: "In the heat of the moment", ja: "興奮して、かっとなって" },
        { en: "It takes one to know one", ja: "お互い様だ" },
        { en: "Keep something at bay", ja: "～を寄せ付けない" },
        { en: "Kill two birds with one stone", ja: "一石二鳥" },
        { en: "Let off steam", ja: "ストレスを発散する" },
        { en: "Look before you leap", ja: "転ばぬ先の杖" },
        { en: "Make ends meet", ja: "やりくりする、収支を合わせる" },
        { en: "Method to my madness", ja: "変に見えても考えがある" },
        { en: "Not a spark of decency", ja: "良心のかけらもない" },
        { en: "Off the hook", ja: "責任を逃れて、苦境を脱して" },
        { en: "Off the record", ja: "非公式に、オフレコで" },
        { en: "Once bitten, twice shy", ja: "あつものに懲りてなますを吹く" },
        { en: "Out of the blue", ja: "突然に" },
        { en: "Picture paints a thousand words", ja: "百聞は一見に如かず" },
        { en: "Put wool over other people's eyes", ja: "人を騙す" },
        { en: "Rain on someone's parade", ja: "人の楽しみを台無しにする" },
        { en: "Skeletons in the closet", ja: "隠しておきたい秘密" },
        { en: "Steal someone's thunder", ja: "人のお株を奪う" },
        { en: "Take with a grain of salt", ja: "話半分に聞く" },
        { en: "Taste of your own medicine", ja: "しっぺ返し" },
        { en: "The ball is in your court", ja: "次はあなたの番だ" },
        { en: "The whole nine yards", ja: "何もかも、すべて" },
        { en: "Throw caution to the wind", ja: "思い切ってやる" },
        { en: "Variety is the spice of life", ja: "変化は人生のスパイス" },
        { en: "Wear your heart on your sleeve", ja: "感情を露わにする" },
        { en: "You can't judge a book by its cover", ja: "人は見かけによらぬもの" },
        { en: "Zero tolerance", ja: "断固として許さないこと" },
        { en: "A hot potato", ja: "厄介な問題" },
        { en: "Against the clock", ja: "時間を争って" },
        { en: "At the drop of a hat", ja: "即座に" },
        { en: "Back to square one", ja: "振り出しに戻る" }
    ],
    advanced: [
        { en: "Play it by ear", ja: "臨機応変に対応する" },
        { en: "Cut to the chase", ja: "本題に入る、要点を言う" },
        { en: "Beat a dead horse", ja: "済んだことを蒸し返す" },
        { en: "Ballpark figure", ja: "概算" },
        { en: "Big cheese", ja: "重要人物" },
        { en: "Black sheep", ja: "厄介者" },
        { en: "Blue collar", ja: "肉体労働者" },
        { en: "White collar", ja: "事務労働者" },
        { en: "Bottleneck", ja: "障害、狭き門" },
        { en: "Brainstorm", ja: "ブレインストーミング" },
        { en: "Cold turkey", ja: "きっぱりと（やめる）" },
        { en: "Couch potato", ja: "テレビばかり見ている人" },
        { en: "Dark horse", ja: "ダークホース（未知の実力者）" },
        { en: "Early bird", ja: "早起きの人" },
        { en: "Night owl", ja: "夜型の人" },
        { en: "Eager beaver", ja: "仕事熱心な人" },
        { en: "Face the music", ja: "報いを受ける" },
        { en: "Fair weather friend", ja: "調子のいい時だけの友達" },
        { en: "Fifth wheel", ja: "邪魔者" },
        { en: "Fish out of water", ja: "場違いな感じ" },
        { en: "Full of beans", ja: "元気いっぱい" },
        { en: "Go the extra mile", ja: "一層の努力をする" },
        { en: "Head over heels", ja: "ぞっこん" },
        { en: "Hit the road", ja: "出発する" },
        { en: "In the loop", ja: "事情に通じて" },
        { en: "In the red", ja: "赤字で" },
        { en: "In the black", ja: "黒字で" },
        { en: "Jack of all trades", ja: "何でも屋" },
        { en: "Jump the gun", ja: "早まる" },
        { en: "Keep a stiff upper lip", ja: "困難に動じない" },
        { en: "Kick the bucket", ja: "死ぬ（俗語）" },
        { en: "Knock on wood", ja: "幸運を祈る（魔除け）" },
        { en: "Let one's hair down", ja: "くつろぐ" },
        { en: "Loose cannon", ja: "何をするかわからない危険人物" },
        { en: "Make a mountain out of a molehill", ja: "大げさに騒ぐ" },
        { en: "Mum's the word", ja: "内緒にしておく" },
        { en: "Neck of the woods", ja: "近所、界隈" },
        { en: "No brainer", ja: "考えるまでもないこと" },
        { en: "Old school", ja: "古風な、伝統的な" },
        { en: "On cloud nine", ja: "最高に幸せ" },
        { en: "On the fence", ja: "迷っている" },
        { en: "On the same page", ja: "意見が一致して" },
        { en: "Out of this world", ja: "素晴らしい" },
        { en: "Over the moon", ja: "大喜びして" },
        { en: "Over the top", ja: "やりすぎ" },
        { en: "Paint the town red", ja: "飲み歩いて大騒ぎする" },
        { en: "Pass the buck", ja: "責任転嫁する" },
        { en: "Piece of work", ja: "厄介な人" },
        { en: "Pipe dream", ja: "夢物語" },
        { en: "Play hard to get", ja: "気のないふりをする" },
        { en: "Poker face", ja: "ポーカーフェイス" },
        { en: "Put one's foot in one's mouth", ja: "失言する" },
        { en: "Raining cats and dogs", ja: "土砂降り" },
        { en: "Read between the lines", ja: "行間を読む" },
        { en: "Red tape", ja: "お役所仕事" },
        { en: "Ring a bell", ja: "心当たりがある" },
        { en: "Rock the boat", ja: "波風を立てる" },
        { en: "Rule of thumb", ja: "経験則" },
        { en: "Save for a rainy day", ja: "万一に備えて貯金する" },
        { en: "Short fuse", ja: "短気" },
        { en: "Sitting duck", ja: "いいカモ" },
        { en: "Sleep like a log", ja: "ぐっすり眠る" },
        { en: "Smell a rat", ja: "怪しいと感じる" },
        { en: "Spill the tea", ja: "ゴシップを話す" },
        { en: "Straight from the horse's mouth", ja: "確かな筋から" },
        { en: "Take a rain check", ja: "またの機会にする" },
        { en: "Take the cake", ja: "最悪だ（または最高だ）" },
        { en: "The tip of the iceberg", ja: "氷山の一角" },
        { en: "Throw the book at", ja: "厳罰に処す" },
        { en: "Tie the knot", ja: "結婚する" },
        { en: "Touch and go", ja: "際どい状況" },
        { en: "Turn a blind eye", ja: "見て見ぬふりをする" },
        { en: "Under the thumb", ja: "言いなりになって" },
        { en: "Walk on eggshells", ja: "慎重に振る舞う" },
        { en: "Wet blanket", ja: "座をしらけさせる人" },
        { en: "Wild goose chase", ja: "無駄な追求" },
        { en: "Wolf in sheep's clothing", ja: "羊の皮を被った狼" },
        { en: "Wrap it up", ja: "終わりにする" },
        { en: "Written all over one's face", ja: "顔に書いてある" },
        { en: "You scratch my back, I'll scratch yours", ja: "持ちつ持たれつ" },
        { en: "Zip your lip", ja: "口を閉じる" },
        { en: "Go cold turkey", ja: "（薬物などを）きっぱりやめる" },
        { en: "Blow off steam", ja: "憂さ晴らしをする" },
        { en: "Close call", ja: "危機一髪" },
        { en: "Double cross", ja: "裏切る" },
        { en: "Drop the ball", ja: "へまをする" },
        { en: "Eye opener", ja: "目から鱗が落ちること" },
        { en: "Food for thought", ja: "考える材料" },
        { en: "Go down in flames", ja: "派手に失敗する" },
        { en: "Go with the flow", ja: "流れに身を任せる" },
        { en: "Have a blast", ja: "とても楽しむ" },
        { en: "In a pickle", ja: "困った状況にある" },
        { en: "Keep your chin up", ja: "元気を出して" },
        { en: "Like a fish out of water", ja: "居心地が悪い" },
        { en: "Make a scene", ja: "騒ぎ立てる" }
    ]
};
